apiVersion: console.openshift.io/v1
kind: ConsoleLink
metadata:
  name: cpd-console
spec:
  applicationMenu:
    section: ACE
  # Update with valid https url
  href: https://cpd-tools.apps.dr.seatechit.com.vn
  location: ApplicationMenu
  text: CPD Console
